version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - '3005:6379' # Map port 3005 on the host to port 6379 on the Redis container
    volumes:
      - redis_data:/data # Optional: persist data

volumes:
  redis_data:
